name: example_ffi_generation
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <3.0.0'

dev_dependencies:
  dart_ffi_bindings_generator: 
    path: '../'

dart_ffi_bindings_generator:
  libclang_dylib: './tool'
  headers:
    - 'a.h'
    - 'b.h'
    - 'c.h'