include: package:pedantic/analysis_options.1.8.0.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
#   exclude:
#     - path/to/excluded/files/**
